# Programma 2
### Le dipendenze dei due notebook sono specificate in _requirements.txt_, le librerie possono essere installate direttamente tramite pip e il file dei requisiti: _"pip install -r requirements.txt"_

## Annotazione Linguistica
La funzione di annotazione ricalca quella utilizzata per il programma numero 1, con la sola differenza che l'elemento _"lemmi"_ non viene aggiunto, non essendo necessario in questo programma.

In [2]:
import nltk
from nltk.corpus import wordnet
import string

class Annotated:
    def __init__(self , sentences, tokenized_sentences, tokens, pos):
        self.sentences = sentences
        self.tokenized_sentences = tokenized_sentences
        self.tokens = tokens
        self.pos = pos

def open_file(path):

    with open(path, "r", encoding = 'utf-8') as infile:
        content = infile.read()
    return content

def change_treebank(treebank_tag):

    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

def annota(testo):

    frasi_mom = nltk.tokenize.sent_tokenize(testo)
    frasi = []
    all_tokens = []
    all_pos_tagged = []

    for frase in frasi_mom:
        tokens = nltk.tokenize.word_tokenize(frase)
        no_punc_tokens = [i for i in tokens if (i not in string.punctuation) and (i != "’" and i != '”' and i != '“')]
        frasi.append(no_punc_tokens)
        all_tokens.extend(no_punc_tokens)
    
    

    all_pos_tagged = nltk.tag.pos_tag(all_tokens)

    result = Annotated(frasi_mom, frasi, all_tokens, all_pos_tagged)
    return result


corpus_annotato = annota(open_file("Corpus Letterario 1.txt"))

## I top-50 Sostantivi, Avverbi e Aggettivi più frequenti
Le funzioni _display_with_title_ e _get_top_ creano un DataFrame (la seconda funzione) e un titolo (la prima funzione) per ogni funzione che verrò invocata. _get_top_ prende in input un oggetto che ha come chiavi i token o gli n-grammi e come valori dei numeri, in questo caso la loro frequenza, n indica i top n elementi che si vogliono prendere in considerazione per frequenza decrescente, Col1 e Col2 sono invece i titoli delle colonne.

_get_pos_freq_ prende in input il corpus annotato e il PoS del quale si vogliono estrarre le parole per averne la frequenza, viene eseguita specificamente per tre PoS: Sostantivi, Avverbi e Aggettivi, come richiesto dalle specifiche.

In [3]:
from IPython.display import display, Markdown

def display_with_title(df, title):
    display(Markdown(f"### {title}"))
    display(df)

In [4]:
import pandas as pd

def get_top(obj, n, Col1, Col2):
    df = pd.DataFrame(obj.items(), columns=[Col1, Col2])
    df = df.astype({Col1: str, Col2: float})
    df = df.sort_values(by=Col2, ascending=False)
    df = df.head(n)
    df = df.reset_index(drop=True)
    return df

In [5]:
def get_pos_freq(corpus, type):
    vocabulary = []
    frequencies = {}

    if(type == 'NOUN'):
        for i in list(set(corpus.pos)):
            if(i[1].startswith('N')):
                vocabulary.append(i[0])

    elif(type == 'ADV'):
        for i in list(set(corpus.pos)):
            if(i[1].startswith('R')):
                vocabulary.append(i[0])

    elif(type == 'ADJ'):
        for i in list(set(corpus.pos)):
            if(i[1].startswith('J')):
                vocabulary.append(i[0])

    else:
        return 'Errore! Inserisci un PoS valido e ritenta'

    for i in vocabulary:
        frequencies[i] = corpus.tokens.count(i)

    return frequencies

sostantivi = get_top(get_pos_freq(corpus_annotato, 'NOUN'), 50, 'N-Grammi', 'Frequenza')
avverbi = get_top(get_pos_freq(corpus_annotato, 'ADV'), 50, 'N-Grammi', 'Frequenza')
aggettivi = get_top(get_pos_freq(corpus_annotato, 'ADJ'), 50, 'N-Grammi', 'Frequenza')

display_with_title(sostantivi, 'Sostantivi')

display_with_title(avverbi, 'Avverbi')

display_with_title(aggettivi, 'Aggettivi')

### Sostantivi

     N-Grammi  Frequenza
0      Copper       85.0
1           s       71.0
2           t       61.0
3     Uragawa       51.0
4      Kitami       50.0
5         one       31.0
6   Yamaguchi       31.0
7         out       27.0
8        face       19.0
9       uncle       19.0
10     matter       16.0
11     people       16.0
12       back       15.0
13        way       14.0
14       know       14.0
15       time       14.0
16  professor       13.0
17       didn       13.0
18     couldn       12.0
19      Tokyo       12.0
20   students       11.0
21      while       11.0
22   everyone       11.0
23  something       11.0
24   telegram       10.0
25    thought       10.0
26       eyes       10.0
27     moment       10.0
28      class       10.0
29         So       10.0
30       hand        9.0
31       city        9.0
32    friends        9.0
33     anyone        9.0
34      right        9.0
35     reason        8.0
36       seat        8.0
37       left        8.0
38       head        8.0
39        day        8.0
40       rain        7.0
41       cars        7.0
42      point        7.0
43    feeling        7.0
44       home        7.0
45      spoke        7.0
46       desk        7.0
47      think        7.0
48       look        7.0
49      Fried        7.0

### Avverbi

     N-Grammi  Frequenza
0           s       71.0
1           t       61.0
2          as       40.0
3         all       37.0
4          up       34.0
5       there       31.0
6         out       27.0
7       about       24.0
8          so       22.0
9        then       20.0
10       even       18.0
11        not       17.0
12       down       16.0
13       just       15.0
14       back       15.0
15      still       15.0
16     little       14.0
17        now       13.0
18     before       11.0
19        too       10.0
20       eyes       10.0
21         So       10.0
22     around        9.0
23       once        9.0
24        off        9.0
25      right        9.0
26      again        9.0
27     really        8.0
28       here        8.0
29       well        7.0
30       Then        7.0
31         As        7.0
32       away        6.0
33      first        6.0
34      never        6.0
35       long        5.0
36       very        5.0
37    quietly        5.0
38       hard        5.0
39      along        5.0
40       Well        5.0
41     always        5.0
42       only        5.0
43   suddenly        5.0
44       Even        5.0
45     lonely        4.0
46        far        4.0
47       more        4.0
48       also        4.0
49  somewhere        4.0

### Aggettivi

      N-Grammi  Frequenza
0            s       71.0
1            t       61.0
2         like       22.0
3         even       18.0
4       little       14.0
5        other       13.0
6       inside       10.0
7        small       10.0
8        right        9.0
9          own        9.0
10        left        8.0
11       young        8.0
12        good        7.0
13        such        7.0
14         let        7.0
15       light        6.0
16       first        6.0
17       human        6.0
18        tide        5.0
19       fried        5.0
20      silent        5.0
21        only        5.0
22        long        5.0
23      single        5.0
24        hard        5.0
25        last        5.0
26       ocean        4.0
27        high        4.0
28        many        4.0
29      lonely        4.0
30  electrical        4.0
31         wet        4.0
32      unable        4.0
33        next        4.0
34    stubborn        4.0
35       that.        4.0
36    straight        4.0
37     rooftop        4.0
38        full        4.0
39       roofs        4.0
40        more        4.0
41       smile        4.0
42        sure        4.0
43       forth        3.0
44        able        3.0
45       whole        3.0
46        same        3.0
47      bottom        3.0
48        dark        3.0
49     strange        3.0

## Top-20 n-grammi più frequenti
La funzione _get_ngrammi_ prende in input il corpus annotato e la dimensione degli n-grammi che si vogliono analizzare tramite un for implicto che prende gli n-grammi e li unisce in un'unica stringa. Rrestituisce un oggetto che contiene come chiave il n-gramma e come valore la sua frequenza nel corpus. Viene richiamata per n = [1, 2, 3, 4, 5] e poi con le funzioni definite nella cella precedente immesse in un DataFrame.

In [6]:
def get_ngrammi(corpus, n):
    
    ngrammi = [', '.join(corpus.tokens[i : i + n]) for i in range(len(corpus.tokens) - n + 1)]
    ngrammi_vocab = list(set(ngrammi))
    frequencies = {}

    for i in ngrammi_vocab:
        frequencies[i] = ngrammi.count(i)
   
    return frequencies

unigrammi = get_top(get_ngrammi(corpus_annotato, 1), 20, 'N-Grammi', 'Frequenza')
bigrammi = get_top(get_ngrammi(corpus_annotato, 2), 20, 'N-Grammi', 'Frequenza')
trigrammi= get_top(get_ngrammi(corpus_annotato, 3), 20, 'N-Grammi', 'Frequenza')
tetragrammi = get_top(get_ngrammi(corpus_annotato, 4), 20, 'N-Grammi', 'Frequenza')
quintigrammi = get_top(get_ngrammi(corpus_annotato, 5), 20, 'N-Grammi', 'Frequenza')

display_with_title(unigrammi, "Unigrammi")
display_with_title(bigrammi, "Bigrammi")
display_with_title(trigrammi, "Trigrammi")
display_with_title(tetragrammi, "Tetragrammi")
display_with_title(quintigrammi, "Quintigrammi")

### Unigrammi

   N-Grammi  Frequenza
0       the      302.0
1        to      177.0
2       and      174.0
3         a      147.0
4        of      140.0
5       was      137.0
6        he      117.0
7       his      105.0
8        in       93.0
9      that       92.0
10   Copper       85.0
11       it       79.0
12        s       71.0
13        t       61.0
14       at       59.0
15      you       53.0
16      had       53.0
17  Uragawa       51.0
18   Kitami       50.0
19      him       49.0

### Bigrammi

          N-Grammi  Frequenza
0          in, the       28.0
1          of, the       25.0
2          he, was       16.0
3          to, the       15.0
4          at, the       14.0
5          didn, t       13.0
6         came, to       13.0
7        Copper, s       12.0
8          he, had       12.0
9          it, was       12.0
10       couldn, t       12.0
11      his, uncle       12.0
12         on, the       12.0
13  the, professor       11.0
14     Copper, had       10.0
15          was, a        9.0
16         in, his        9.0
17      of, people        9.0
18    matter, what        9.0
19        the, two        9.0

### Trigrammi

                N-Grammi  Frequenza
0          he, couldn, t        5.0
1           it, came, to        5.0
2   matter, what, anyone        5.0
3           the, two, of        5.0
4       no, matter, what        5.0
5        and, his, uncle        4.0
6         when, it, came        4.0
7       of, people, were        4.0
8       No, matter, what        4.0
9            he, didn, t        3.0
10      it, seemed, that        3.0
11      Copper, s, uncle        3.0
12        While, he, was        3.0
13   didn, t, understand        3.0
14            he, had, a        3.0
15          out, of, the        3.0
16       couldn, t, help        3.0
17      here, and, there        3.0
18         What, in, the        3.0
19         of, the, city        3.0

### Tetragrammi

                       N-Grammi  Frequenza
0            when, it, came, to        4.0
1      No, matter, what, anyone        4.0
2       Copper, and, his, uncle        3.0
3         with, all, his, might        3.0
4          What, in, the, world        3.0
5            the, two, of, them        3.0
6   bright, expression, on, his        2.0
7          couldn, t, help, but        2.0
8          what, was, going, on        2.0
9           had, been, able, to        2.0
10        Tofu, do, the, speech        2.0
11   rising, and, falling, like        2.0
12         the, city, of, Tokyo        2.0
13       lunch, box, every, day        2.0
14           for, a, while, but        2.0
15         Fried, Tofu, do, the        2.0
16      the, streets, of, Tokyo        2.0
17      he, didn, t, understand        2.0
18    rain, continued, to, fall        2.0
19         down, at, the, Ginza        2.0

### Quintigrammi

                                 N-Grammi  Frequenza
0         down, at, the, Ginza, Boulevard        2.0
1              make, Fried, Tofu, do, the        2.0
2          a, bright, expression, on, his        2.0
3       bright, expression, on, his, face        2.0
4          No, matter, what, anyone, says        2.0
5                s, make, Fried, Tofu, do        2.0
6         pedaling, with, all, his, might        2.0
7            Fried, Tofu, do, the, speech        2.0
8          much, at, first, Mizutani, was        1.0
9              In, fact, there, could, be        1.0
10     before, Actually, this, change, in        1.0
11           forth, Among, such, a, group        1.0
12       narrow, space, between, the, two        1.0
13  people, were, at, once, materializing        1.0
14           hoist, himself, up, or, even        1.0
15       jumped, up, and, pushed, forward        1.0
16     laughing, If, Tokyo, s, population        1.0
17     pictures, Uragawa, knew, only, the        1.0
18            and, the, falling, tide, of        1.0
19                badly, You, can, t, say        1.0

## Top-20 n-grammi di PoS più frequenti
La funzoine _get_ngrammi_pos_ è una funzione che, analogamente a quella precedente, calcola la frequenza degli _n-grammi_ e la restituisce in un oggetto. Dovendo però calcolare i **top 20 n-grammi di PoS** dall'array iniziale che contiene sia il token che la sua _Part of Speech_ si _"filtrano"_ solamente le Part of Speech con il primo ciclo for. Il secondo invece calcola la frequenza degli n-grammi filtrati in _only_pos_

In [7]:
def get_ngrammi_pos(corpus, n):
    
    ngrammi_pos = [tuple(corpus.pos[i : i + n]) for i in range(len(corpus.pos) - n + 1)]
    only_pos = []
    freq = {}

    for ngram_pos in ngrammi_pos:
        npos = [pos for token, pos in ngram_pos]
        only_pos.append(npos)
    
    for j in only_pos:
        freq[', '.join(j)] = only_pos.count(j) 
    
    return freq

unigrammi_pos = get_top(get_ngrammi_pos(corpus_annotato, 1), 20, 'N-Grammi', 'Frequenza')
bigrammi_pos = get_top(get_ngrammi_pos(corpus_annotato, 2), 20, 'N-grammi', 'Frequenza')
trigrammi_pos = get_top(get_ngrammi_pos(corpus_annotato, 3), 20, 'N-Grammi', 'Frequenza')

display_with_title(unigrammi_pos, "Unigrammi di PoS")
display_with_title(bigrammi_pos, "Bigrammi di PoS")
display_with_title(trigrammi_pos, "Trigrammi di PoS")

### Unigrammi di PoS

   N-Grammi  Frequenza
0        NN      995.0
1        IN      861.0
2        DT      662.0
3       VBD      549.0
4       PRP      456.0
5        RB      453.0
6        JJ      398.0
7       NNP      384.0
8        CC      263.0
9        VB      259.0
10      NNS      252.0
11      VBG      193.0
12       TO      180.0
13     PRP$      159.0
14      VBN      140.0
15      VBP      120.0
16       MD       92.0
17      VBZ       62.0
18       RP       56.0
19       CD       53.0

### Bigrammi di PoS

    N-grammi  Frequenza
0     DT, NN      349.0
1     IN, DT      291.0
2     NN, IN      260.0
3     JJ, NN      173.0
4   PRP, VBD      170.0
5     DT, JJ      151.0
6    IN, PRP      116.0
7     TO, VB      108.0
8    NN, VBD      107.0
9   NNP, VBD      105.0
10  PRP$, NN       99.0
11    NN, CC       98.0
12    NN, NN       97.0
13    IN, NN       91.0
14    RB, IN       85.0
15   VBD, RB       82.0
16   VBD, DT       77.0
17   VBD, IN       73.0
18    MD, VB       72.0
19   IN, NNP       72.0

### Trigrammi di PoS

        N-Grammi  Frequenza
0     IN, DT, NN      154.0
1     DT, JJ, NN       94.0
2     DT, NN, IN       90.0
3     NN, IN, DT       86.0
4     IN, DT, JJ       66.0
5     JJ, NN, IN       50.0
6   IN, PRP$, NN       49.0
7   IN, PRP, VBD       47.0
8     RB, IN, DT       43.0
9     NN, IN, NN       40.0
10   DT, NN, VBD       36.0
11    DT, NN, CC       36.0
12   NN, IN, PRP       35.0
13    DT, NN, NN       33.0
14   VBD, DT, NN       33.0
15   PRP, MD, VB       33.0
16   VBD, TO, VB       32.0
17    NN, DT, NN       28.0
18   VBD, DT, JJ       28.0
19  PRP, VBD, IN       26.0

## Top-10 Bigrammi Aggettivo-Sostantivo ordinati per frequenza
La funzione _adj_noun_bigrams_ divide il corpus per bigrammi con annessa la PoS di ogni token, filtra poi l'array restituendo solo i bigrammi che rispettano l'ordine (Aggetivo, Sostantivo). La frequenza di questi bigrammi all'interno del corpus viene poi calcolata invece da _freq_bigrams_ che restituisce un array di due oggetti: un oggetto contenente i bigrammi e la loro frequenza (con il formato per inserirli in un DataFrame) e un altro oggetto identico ma senza una modifica per le chiavi (per richiamare e utilizzare il risultato della funzione in altre funzioni).

In [8]:
def adj_noun_bigrams(corpus):
    
    bigrammi = [corpus.pos[i : i + 2] for i in range(len(corpus.pos) - 2 + 1)]
    adj_noun = []

    for i in bigrammi:
        if(i[0][1].startswith('J') and (i[1][1].startswith('N'))):
            adj_noun.append(tuple(i))
    return adj_noun

def freq_bigrams(bigrammi):

    frequencies = {}
    raw_freq = {}

    for j in bigrammi:
        freq = raw_freq.get(j, 0) + 1
        raw_freq[j] = freq
        npos = ', '.join(f"{token} ({pos})" for token, pos in j)
        frequencies[npos] = freq

    return frequencies, raw_freq

display_with_title(get_top(freq_bigrams(adj_noun_bigrams(corpus_annotato))[0], 10, 'N-Grammi', 'Frequenza'), 'Top 10 Bigrammi Aggettivo-Nome')

### Top 10 Bigrammi Aggettivo-Nome

                       N-Grammi  Frequenza
0          young (JJ), man (NN)        5.0
1      human (JJ), beings (NNS)        3.0
2             s (JJ), hand (NN)        2.0
3       little (JJ), paper (NN)        2.0
4           high (JJ), bar (NN)        2.0
5         fried (JJ), tofu (NN)        2.0
6    rooftop (JJ), Copper (NNP)        2.0
7          last (JJ), year (NN)        2.0
8         first (JJ), year (NN)        2.0
9  bright (JJ), expression (NN)        2.0

## Top-10 Bigrammi Aggettivo-Sostantivo ordinati per probabilità condizionata
_prob_cond_ richiama la funzione _adj_noun_bigrams_ creata nella cella precedente per avere già l'array filtrato secondo la richiesta. Utilizzo _freq_bigrams_ per prendere le frequenze dei bigrammi e, tramite il ciclo for calcolo la probabilità condizionata dei bigrammi, in t1_freq calcola la frequenza del primo token del bigramma e poi il valore da inserire nel dizionario viene calcolato direttamente all'assegnazione. Il ritorno è un array di due oggetti come nella funzione precedente.

In [9]:
def prob_cond(corpus):

    bigrams = adj_noun_bigrams(corpus)
    bi_freq = freq_bigrams(bigrams)[1]
    probab_condizionata = {}
    raw_probab_condizionata = {}

    for bigram, freq in bi_freq.items():
        key = ', '.join(f"{token} ({pos})" for token, pos in bigram)
        t1_freq = corpus.pos.count(bigram[0])
        cond_p = freq/t1_freq
        probab_condizionata[key] = cond_p
        raw_probab_condizionata[bigram] = cond_p

    return probab_condizionata, raw_probab_condizionata

display_with_title(get_top(prob_cond(corpus_annotato)[0],10, 'N-Grammi', 'Probabilità Condizionata'), 'Top-10 Bigrammi Agg.-Sost. ordinati per probabilità condizionata')

### Top-10 Bigrammi Agg.-Sost. ordinati per probabilità condizionata

                          N-Grammi  Probabilità Condizionata
0         bandaged (JJ), hand (NN)                       1.0
1         rooftop. (JJ), Yes (NNP)                       1.0
2         tide (JJ), Staring (NNP)                       1.0
3        highest (JJS), point (NN)                       1.0
4        invisible (JJ), tide (NN)                       1.0
5       various (JJ), selves (NNS)                       1.0
6      unannotated (JJ), work (NN)                       1.0
7        flustered (JJ), face (NN)                       1.0
8  seven-story (JJ), building (NN)                       1.0
9      penmanship (JJ), class (NN)                       1.0

## Top-10 Bigrammi Aggettivo-Sostantivo ordinati per probabilità congiunta
Sfruttando la funzione della probabilità condizionata della cella precedente, la funzione _prob_cong_ caclola la probabilità congiunta dei bigrammi. Nel _for_ viene preso il primo token del bigramma e se ne calcola la frequenza, dopo al dizionario viene aggiunta la chiave (il bigramma) e la probabilità congiunta: $P(A)*P(B|A)$

In [10]:
def prob_cong(corpus):
    bigrams = prob_cond(corpus)[1]
    result = {}

    for big, prob in bigrams.items():
        prob_first = corpus.pos.count(tuple(big[0]))/len(corpus.pos)
        key = ', '.join(f"{token} ({pos})" for token, pos in big)
        result[key] = prob * prob_first

    return result
get_top(prob_cong(corpus_annotato), 10, 'N-Grammi', 'Probabilità Congiunta')

                       N-Grammi  Probabilità Congiunta
0          young (JJ), man (NN)               0.000736
1      human (JJ), beings (NNS)               0.000442
2       little (JJ), paper (NN)               0.000294
3          last (JJ), year (NN)               0.000294
4             s (JJ), hand (NN)               0.000294
5  bright (JJ), expression (NN)               0.000294
6         first (JJ), year (NN)               0.000294
7         fried (JJ), tofu (NN)               0.000294
8           high (JJ), bar (NN)               0.000294
9    rooftop (JJ), Copper (NNP)               0.000294

## Top-10 Bigrammi Aggettivo-Sostantivo ordinati per Mutual Information e Local MI
_get_mi_ prende in input il corpus e una stringa 'LMI' o 'MI' a seconda di cosa si vuole calcolare. Le operazioni nel for sono le stesse effettuate per la funzione di prima, in modo da calcolare la frequenza del primo e del secondo token. Successivamente calcola la MI e la aggiunge al dizionario reuslt. Se si richiede la Mutual Information viene restituito il risultato subito, altrimenti calcolo la LMI tramite un altro for e ritorno quella risultante.

In [11]:
import math
def get_mi(corpus, infotype):
    bigrams = adj_noun_bigrams(corpus)
    bi_freq = freq_bigrams(bigrams)[1]
    
    result = {}
    result_mi = {}
    result_lmi = {}

    for big, freq in bi_freq.items():
        token1 = big[0]
        token2 = big[1]
        freq1 = corpus.pos.count(tuple(token1))
        freq2 = corpus.pos.count(tuple(token2))
        MI = math.log((freq*len(corpus.pos))/(freq1*freq2), 2)
        result[big] = MI

    if(infotype == 'MI'):
        for k, v in result.items():
            key = ', '.join(f"{token} ({pos})" for token, pos in k)
            result_mi[key] = v
        return result_mi

    elif(infotype == 'LMI'):
        for big, mi in result.items():
            lmi = mi * bi_freq[big]
            key = ', '.join(f"{token} ({pos})" for token, pos in big)
            result_lmi[key] = lmi
        return result_lmi

display_with_title(get_top(get_mi(corpus_annotato, 'MI'), 10, 'Bigrammi', 'MI'), 'Mutual Information')
display_with_title(get_top(get_mi(corpus_annotato, 'LMI'), 10, 'Bigrammi', 'LMI'), 'Local Mutual Information')

### Mutual Information

                                 Bigrammi         MI
0                 real (JJ), whisper (NN)  12.729621
1                   direct (JJ), hit (NN)  12.729621
2          involuntary (JJ), remorse (NN)  12.729621
3                 large (JJ), maroon (NN)  12.729621
4                 vast (JJ), expanse (NN)  12.729621
5                audible (JJ), noise (NN)  12.729621
6              former (JJ), location (NN)  12.729621
7                tide (JJ), Staring (NNP)  12.729621
8              various (JJ), selves (NNS)  12.729621
9  single-minded (JJ), concentration (NN)  12.729621

### Local Mutual Information

                            Bigrammi        LMI
0               young (JJ), man (NN)  47.332932
1           human (JJ), beings (NNS)  30.433975
2       bright (JJ), expression (NN)  22.289316
3                high (JJ), bar (NN)  20.289316
4              fried (JJ), tofu (NN)  19.645460
5              first (JJ), year (NN)  18.815385
6               last (JJ), year (NN)  18.171529
7            little (JJ), paper (NN)  14.888437
8                  s (JJ), hand (NN)  14.475535
9  uncoordinated (JJ), movement (NN)  12.729621

### Bigrammi comuni alle classifiche di MI e LMI
La prima funzione ordina le due classifiche e prende solo i primi 10 elementi. Poi _common_bigrams_ fa un'intersezione tra le due classifiche e restituisce, qualora ve ne fossero, i bigrammi comuni.

In [12]:
def get_top_n_sorted(d, n):
    return sorted(d.items(), key=lambda item: item[1], reverse=True)[:n]

def common_bigrams(corpus):
    top_10_mi = get_top_n_sorted(get_mi(corpus, 'MI'), 10)
    top_10_lmi = get_top_n_sorted(get_mi(corpus, 'LMI'), 10)
    common_bi = set([bigram for bigram, _ in top_10_mi]).intersection([bigram for bigram, _ in top_10_lmi])
    return {' '.join(common_bi): len(common_bi)}

bi_comuni = get_top(common_bigrams(corpus_annotato), 1, 'Bigramma', 'Frequenza')
display_with_title(bi_comuni, 'Bigrammi comuni alle top-10 dei bigrammi per MI e LMI')

### Bigrammi comuni alle top-10 dei bigrammi per MI e LMI

                      Bigramma  Frequenza
0  silver (JJ), droplets (NNS)        1.0

## Calcolo Media della Distribuzione di Frequenza dei Token per Frase
Data la distribuzione di frequenza dei token: $\frac {\sum_0^n(freq(token_n))}{n}$ dove n è la lunghezza in token della frase, la funzione prende in input il corpus e quale vaore si vuole ritornare (max o min secondo il valore della distribuzione). Il primo for filtra le frasi controllando che siano lunghe almeno 10 token e non più di 20. Il secondo invece itera in un arrai contenente le frasi _filtrate_ e calcola la media della distribuzione di frequenza dei token per ogni frase, infine aggiunge a un dizionario la frase e il valore appena calcolato. Le clausole if decidono, a seconda di _min_max_ quale risultato ritornare.

In [13]:
def distr_frasi(corpus, min_max = None):
    filtered_sent = []
    frequencies = get_ngrammi(corpus, 1)
    distr_media = {}
    result = {}

    for i in corpus.tokenized_sentences:
        if(10 <= len(i) <= 20):
            count = sum(1 for token in i if corpus.tokens.count(token) >= 2)
            if(count >= len(i)//2):
                filtered_sent.append(i)
    for j in filtered_sent:
        distr = 0
        key = ' '.join(j)
        for k in j:
            distr += frequencies[k]
        distr_media[key] = (distr/len(j))

    if(min_max == 'min'):
        result[min(distr_media, key=distr_media.get)] = min(distr_media.values())
        return result
    elif(min_max == 'max'):
        result[max(distr_media, key=distr_media.get)] = max(distr_media.values())
        return result
    elif(min_max is None):
        return distr_media
        
display_with_title(get_top(distr_frasi(corpus_annotato, 'max'), 1, 'Frase', 'Media della Distribuzione di Frequenza'), 'Frase con Media della Distr. di Frequenza Massima')
display_with_title(get_top(distr_frasi(corpus_annotato, 'min'), 1, 'Frase', 'Media della Distribuzione di Frequenza'), 'Frase con Media della Distr. di Frequenza Minima')

### Frase con Media della Distr. di Frequenza Massima

,Frase,Media della Distribuzione di Frequenza
0,Tokyo was submerged motionless at the bottom o...,94.5

### Frase con Media della Distr. di Frequenza Minima

,Frase,Media della Distribuzione di Frequenza
0,Then once they ve done their job they go hurry...,12.0

## Markov II Ordine
Dato che il risultato di get_ngrammi restituisce un dizionario con le frequenze e non solamente gli n-grammi richiesti ho creato una funzione apposita per farlo: _ngrammi_frasi_.
Nella funzione che segue, il modello di Markov del secondo ordine, calcola la lunghezza del corpus, le frequenze dei token, dei bigrammi e trigrammi. Nel primo ciclo for si filtrano di nuovo le frasi per lunghezza $10<length<20$. Il secondo for applica esattamente il metodo manuale per calcolare la probabilità di una frase secondo il modello, moltiplica la frequenza del primo token per quella condizionata del primo bigramma, successivamente il for nested continua aggiungendo il trigramma arrivando fino a fine frase. Ogni volta la frase viene salvata come chiave nel dizionario res e la probabilità inserita come suo valore. Avendo costruito la funzione _get_ngrammi_ in modo simile alla funzione _FreqDist_ di **nltk** viene utilizzata questa.

In [14]:
def ngrammi_frasi(frase, n):
    
    ngrammi = [', '.join(frase[i : i + n]) for i in range(len(frase) - n + 1)]
    return ngrammi

In [15]:
def Markov2Order(corpus):
    filtered_sent = []
    len_c = len(corpus.tokens)
    freq_token = get_ngrammi(corpus, 1)
    bigrams_freq = get_ngrammi(corpus, 2)
    trigram_freq = get_ngrammi(corpus, 3)
    res = {}

    for i in corpus.tokenized_sentences:
        if(10 <= len(i) <= 20):
            count = sum(1 for token in i if corpus.tokens.count(token) >= 2)
            if(count >= len(i)//2):
                filtered_sent.append(i)

    for i in filtered_sent:
        bi_frase = ngrammi_frasi(i, 2)
        tri_frase = ngrammi_frasi(i, 3)
        p = (freq_token[i[0]]/len_c)*(bigrams_freq[bi_frase[0]]/freq_token[i[0]])
        for trigram, bigram in zip(tri_frase, bi_frase):
            p *= trigram_freq[trigram]/bigrams_freq[bigram]

        res[' '.join(i)] = p

    return {max(res, key=res.get): max(res.values())}

display_with_title(get_top(Markov2Order(corpus_annotato), 1, 'Frasi', 'Probabilità'), 'Frase con probabilità più alta secondo il modellodi Markov del secondo ordine costruito a partire dal corpus')

### Frase con probabilità più alta secondo il modellodi Markov del secondo ordine costruito a partire dal corpus

                                               Frasi  Probabilità
0  Because it drew out an involuntary remorse for...     0.000147

## NE
Per avere un array contenente le Named Entity dalla funzione _nltk.ne_chunk_ ho creato la funzione _get_NE_, tramite un ciclo for memorizza l'entità e il suo tipo inserendole come tupla nell'array che verrà poi restituito. La funzione _freq_NE_ sfrutta la funzione precedente per ottenere le Named Entities dal corpus, poi ne calcola la frequenza con un ciclo for inserendo i risultati in un dizionario.

In [16]:
def get_NE(corpus):
    NE_tree = nltk.ne_chunk(corpus.pos)
    NE = []

    for node in NE_tree:
        if hasattr(node, 'label'):
            entity = " ".join([token for token, POS in node.leaves()])
            entity_type = node.label()
            NE.append((entity, entity_type))

    return NE

def freq_NE(corpus, ent_type):

    tree = get_NE(corpus)
    res = {}
    for entity, entity_type in tree:
        if(entity_type == ent_type):
            res[entity] = tree.count((entity, entity_type))
    return res

display_with_title(get_top(freq_NE(corpus_annotato, 'PERSON'), 15, 'PERSON', 'Frequenza'), 'Top 15 Elementi per "Person"')
display_with_title(get_top(freq_NE(corpus_annotato, 'GPE'), 15, 'GPE', 'Frequenza'), 'Top 15 Elementi per "GPE"')
display_with_title(get_top(freq_NE(corpus_annotato, 'ORGANIZATION'), 15, 'ORGANIZATION', 'Frequenza'), 'Top 15 Elementi per "Organization"')

### Top 15 Elementi per "Person"

              PERSON  Frequenza
0             Copper       71.0
1            Uragawa       38.0
2             Kitami       28.0
3          Yamaguchi       14.0
4            Gatchin        6.0
5         Fried Tofu        3.0
6           Mizutani        3.0
7               Hori        3.0
8               Tofu        2.0
9                Hey        2.0
10            Kawase        2.0
11        Kitami Don        1.0
12  Kitami Yamaguchi        1.0
13              Okay        1.0
14     Kitami Silent        1.0

### Top 15 Elementi per "GPE"

           GPE  Frequenza
0        Tokyo       11.0
1       Copper        9.0
2       Kitami        7.0
3      Uragawa        5.0
4    Yamaguchi        5.0
5    Shinbashi        1.0
6     Kyōbashi        1.0
7  Electricity        1.0
8      English        1.0
9       Kawase        1.0

### Top 15 Elementi per "Organization"

             ORGANIZATION  Frequenza
0                   Ginza        2.0
1         Ginza Boulevard        2.0
2                  Kitami        2.0
3               Yamaguchi        2.0
4                Kyōbashi        1.0
5           Izu Peninsula        1.0
6                    Come        1.0
7             Ginza Uncle        1.0
8                      No        1.0
9                   World        1.0
10                Uragawa        1.0
11  Uragawa Troublemakers        1.0
12          Ginza Uragawa        1.0
13       Kitami Yamaguchi        1.0
14                   Tell        1.0